drop table if exists backups,audit_logs,documents,prescription_items,leaves,attendance,employees,payments,bills,prescriptions,medicines,lab_tests,medical_records,admissions,appointments,schedules,doctors,departments,patients,users,roles cascade;
create table roles(id serial primary key,name text unique not null);
insert into roles(name) values('admin'),('doctor'),('nurse'),('receptionist'),('lab'),('pharmacist'),('accountant');
create table users(id serial primary key,username text unique not null,password_hash text not null,role_id int not null references roles(id),active text default 'Yes');
create table departments(id serial primary key,name text unique not null,description text);
insert into departments(name) values('General Medicine'),('Cardiology'),('Pediatrics'),('Laboratory'),('Pharmacy'),('Administration');
create table patients(id serial primary key,name text not null,age int,gender text,blood_group text,phone text,address text,created_at timestamptz default now());
create table doctors(id serial primary key,name text not null,department_id int references departments(id),specialization text,phone text);
alter table users add column doctor_id int references doctors(id) on delete set null;
create table schedules(id serial primary key,doctor_id int not null references doctors(id) on delete cascade,day_of_week text not null,start_time time not null,end_time time not null);
create table appointments(id serial primary key,patient_id int not null references patients(id) on delete cascade,doctor_id int not null references doctors(id) on delete cascade,appt_date date not null,appt_time time not null,reason text,status text default 'Scheduled');
create table admissions(id serial primary key,patient_id int not null references patients(id) on delete cascade,doctor_id int references doctors(id),type text default 'Outpatient',room text,admit_date date not null,discharge_date date,status text default 'Admitted');
create table medical_records(id serial primary key,patient_id int not null references patients(id) on delete cascade,doctor_id int references doctors(id),visit_date date default current_date,diagnosis text,treatment text,notes text);
create table lab_tests(id serial primary key,patient_id int not null references patients(id) on delete cascade,doctor_id int references doctors(id),test_name text not null,price numeric(10,2) default 0,status text default 'Requested',sample_date date,result text,file_name text,file_data text);
create table medicines(id serial primary key,name text not null,stock int default 0,unit_price numeric(10,2) default 0,expiry_date date,reorder_level int default 10);
create table prescriptions(id serial primary key,patient_id int not null references patients(id) on delete cascade,doctor_id int references doctors(id),notes text,status text default 'Pending',file_name text,file_data text,created_at timestamptz default now());
create table prescription_items(id serial primary key,prescription_id int not null references prescriptions(id) on delete cascade,medicine_id int references medicines(id),quantity int default 1,dosage text);
create table bills(id serial primary key,patient_id int not null references patients(id) on delete cascade,category text not null,description text,amount numeric(10,2) not null,status text default 'Unpaid',created_at timestamptz default now());
create table payments(id serial primary key,bill_id int not null references bills(id) on delete cascade,amount numeric(10,2) not null,method text default 'Cash',paid_on date default current_date);
create table employees(id serial primary key,name text not null,designation text,department_id int references departments(id),phone text,joined_date date);
create table attendance(id serial primary key,employee_id int not null references employees(id) on delete cascade,att_date date not null,status text default 'Present');
create table leaves(id serial primary key,employee_id int not null references employees(id) on delete cascade,from_date date not null,to_date date not null,reason text,status text default 'Pending');
create table documents(id serial primary key,patient_id int not null references patients(id) on delete cascade,title text not null,file_name text,file_data text,created_at timestamptz default now());
create table audit_logs(id serial primary key,username text,action text,detail text,created_at timestamptz default now());
create table backups(id serial primary key,data jsonb,created_at timestamptz default now());
create index on appointments(doctor_id,appt_date);create index on appointments(patient_id);create index on bills(patient_id);create index on payments(bill_id);create index on lab_tests(patient_id);create index on medical_records(patient_id);
